Feeds.DataFolder = "feeds"
Feeds.Save = true
Mail.Destination = "myemail@example.com"
Mail.Enable = true
Mail.Sender = "rsswatch@example.com"
Mail.Server = "mail.example.com:25"

[[Feeds]]
  Url = "https://en.wikipedia.org/w/index.php?title=RSS&feed=atom&action=history"
  Folder = "misc.wikipedia"

[[Feeds]]
  Url = "https://en.wikipedia.org/w/index.php?title=Special:RecentChanges&feed=atom"
  Filters = [".*", ".*Talk:.*"]
  Folder = "misc.wikipedia"
