DataFolder = "feeds"
MailDestination = "hebz0rl@thaller.ws"
MailDisable = false
MailSender = "rsswatch@thaller.ws"
MailServer = "mail.thaller.ws:25"
SaveFeeds = true
Profile = false
ProfileBind = "localhost:6060"

[LogLevel]
  . = "Debug"

[[Feeds]]
  Url = "https://en.wikipedia.org/w/index.php?title=RSS&feed=atom&action=history"
  Folder = "misc.wikipedia"

[[Feeds]]
  Url = "https://en.wikipedia.org/w/index.php?title=Special:RecentChanges&feed=atom"
  Filters = [".*", ".*Talk:.*"]
  Folder = "misc.wikipedia"

[[Feeds]]
  Url = "http://viruscomix.com/rss.xml"
  Folder = "comics"
