language: go
go:
  - 1.2
  - 1.3
  - tip

before_install:
  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/AlexanderThaller/goimports
  - go get github.com/AlexanderThaller/lint/golint
  - export PATH=$HOME/gopath/bin:$PATH
